### ISSUE TITLE
Mod loading problems

### ISSUE THREAD

**Issue by Infi-power** [IceDragon200/mt-yatm#25]
_(I'm not a native english speaker so I'm sorry if I made any grammar mistakes or typos.)_

`Minetest version 5.7.0-dev`
`(followed the minetest documentation for compiling and installed LuaJIT library for LuaJIT support)`

`OS info: Debian GNU/Linux 11 (bullseye)`

Hello, I came across a post you made in minetest forums about this mod and it got my attention, so I decided to try it out.
However, I tried to load the mod but I failed to successfully initialize the mod.

The way that I tried was enable this mod, `foundation` and `nokore_mods` under `minetest_game`. But when I tried to play a world, minetest gave me this error:
```
ModError: Failed to load and run script from /home/think/minetest/minetest-master/bin/../mods/nokore-mods/nokore_tnt/init.lua:
...etest-master/bin/../mods/nokore-mods/nokore_tnt/init.lua:6: attempt to index global 'foundation' (a nil value)
stack traceback:
	...etest-master/bin/../mods/nokore-mods/nokore_tnt/init.lua:6: in main chunk
Check debug.txt for details.
```

But `foundation` was enabled under it, so I thought "It might need the nokore game itself", so I installed the `nokore_game` and tried to load the mod again under `nokore_game` (and yes I enabled the dependencies as well).

But when I tried to load the mod, minetest gave me a different error:

```
ModError: Failed to load and run script from /home/think/minetest/minetest-master/bin/../games/nokore-game/mods/nokore_prelude/init.lua:
..../mods/foundation/foundation_node_sounds/node_sounds.lua:15: a name is required for node sound registries
stack traceback:
	[C]: in function 'assert'
	..../mods/foundation/foundation_node_sounds/node_sounds.lua:15: in function 'initialize'
	...master/bin/../mods/foundation/foundation_class/class.lua:107: in function 'new'
	...er/bin/../games/nokore-game/mods/nokore_prelude/init.lua:8: in main chunk
Check debug.txt for details.
```

I looked into source code, but I couldn't find anything wrong. I couldn't understand what `name` is requied.
I hope somebody can assist further for fixing this issue.
Have a great day/night.

**Comment by IceDragon200** [comment]
First up, thank you for trying my mod.

And I apologize for the mess that the dependencies are currently.

`nokore`'s mods are not intended to be loaded wholesale under `minetest_game`, since it's a re-implementation of some `minetest_game` features, only a handful of mods under it can safely work there (I don't have a list off the top of my head)

While I don't believe it would outright crash the game if you enabled all of it, you will end up with a mess of worldgen.

That aside, I'll explain what happened:

## Minetest Game

```
ModError: Failed to load and run script from /home/think/minetest/minetest-master/bin/../mods/nokore-mods/nokore_tnt/init.lua:
...etest-master/bin/../mods/nokore-mods/nokore_tnt/init.lua:6: attempt to index global 'foundation' (a nil value)
stack traceback:
	...etest-master/bin/../mods/nokore-mods/nokore_tnt/init.lua:6: in main chunk
Check debug.txt for details.
```

I forgot to include the `foundation_base` dependency in the `nokore_tnt` mod, I've pushed a fix to master, so that one should be resolved.

Also I've made a compatibility mod for it https://github.com/IceDragon200/mt-nokore-default-compat

It's been quite some time since I've last tested it under `minetest_game` so some breakage was expected.

## Nokore Game

```
ModError: Failed to load and run script from /home/think/minetest/minetest-master/bin/../games/nokore-game/mods/nokore_prelude/init.lua:
..../mods/foundation/foundation_node_sounds/node_sounds.lua:15: a name is required for node sound registries
stack traceback:
	[C]: in function 'assert'
	..../mods/foundation/foundation_node_sounds/node_sounds.lua:15: in function 'initialize'
	...master/bin/../mods/foundation/foundation_class/class.lua:107: in function 'new'
	...er/bin/../games/nokore-game/mods/nokore_prelude/init.lua:8: in main chunk
Check debug.txt for details.
```

The version of `nokore_game` that was available was out of date, I was sitting on the node sounds update locally.

## Harmonia Scarred World

The reason everything was so broken, I was working on a completely different game: https://github.com/IceDragon200/mt-harmonia-scarred-world

If you're interested you can pull that repository down with its submodules, it should be a relatively stable experience.

Granted there isn't much to do, there are no recipes or even gameplay for that matter, I've been mostly fleshing out ideas and building the underlying systems for those ideas.

You are free to play around in creative with it however

**Comment by Infi-power** [comment]
Thank you, the mod is working now! While I can't play survival game with this mod, I can do crazy stuff while I play creative mode.
Again, thank you for making this mod and assisting me.
