### ISSUE TITLE
remove dependencies on nokore_* mods

### ISSUE THREAD

**Issue by tigercoding56** [IceDragon200/mt-yatm#26]
i cannot find the nokore_proxy and nokore_ui mods anywhere  ,

**Comment by IceDragon200** [comment]
https://github.com/IceDragon200/mt-nokore-mods 

* https://github.com/IceDragon200/mt-nokore-mods/tree/master/nokore_ui
* https://github.com/IceDragon200/mt-nokore-mods/tree/master/nokore_proxy

The mod is in a state of being reworked slowly so it relies on base modules from nokore which is my attempt at replacing minetest_game for my own game: https://github.com/IceDragon200/mt-harmonia-scarred-world

I would recommend using the releases it provides instead of trying to figure things out yourself: https://github.com/IceDragon200/mt-harmonia-scarred-world/releases/tag/0.0.3 for example

To play yatm under `minetest_game`, you will need `foundation`, parts of `nokore`  and `yatm` itself.

Keep in mind I am not actively keeping compatibility with `default`, so there are breaking changes every now and then.

If you have any other questions feel free to ask, I'll close this issue for now.
